services:
  cli:
    image: golang-cli
    #cpus: 1
    build:
      dockerfile: docker/Dockerfile.cli
      args:
        APP_USER_ID: "${APP_USER_ID}"
    user: "${APP_USER_ID}"
    container_name: cli-${USER}
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "${SITE_PORT}:${SITE_PORT}"
      - "${MOBILE_PORT_OZ}:${MOBILE_PORT_OZ}"
      - "${MOBILE_PORT_SF}:${MOBILE_PORT_SF}"
      - "${MOBILE_PORT_SA}:${MOBILE_PORT_SA}"
      - "${MOBILE_PORT_ST}:${MOBILE_PORT_ST}"
      - "${MONITOR_PORT}:${MONITOR_PORT}"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ../go/pkg:/go/pkg
      - home_cli_data:/home/cli
      - .:/app
      - ./logs:/app/logs
    #profiles:
    #  - donotstart

  redis:
    image: redis
    hostname: redis-${USER}
    container_name: redis-${USER}
    environment:
      - TZ=Europe/Moscow
    command: redis-server --save 60 1 --loglevel warning

  redis-cli:
    image: redis
    container_name: redis-cli-${USER}
    command: redis-cli -h redis-${USER}
    environment:
      - TZ=Europe/Moscow
    profiles:
      - donotstart

volumes:
    home_cli_data:

networks:
  dev:
    name: dev
    external: true
