services:
  cli:
    image: golang-cli
    #cpus: 1
    build:
      dockerfile: docker/Dockerfile.cli
      args:
        APP_USER_ID: "${APP_USER_ID}"
    user: "${APP_USER_ID}"
    working_dir: /app
    stdin_open: true
    tty: true
    networks:
      - dev
    ports:
      - "${SITE_PORT}:${SITE_PORT}"
      - "${MOBILE_PORT}:${MOBILE_PORT}"
      - "${MONITOR_PORT}:${MONITOR_PORT}"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ../go/pkg:/go/pkg
      - home_cli_data:/home/cli
      - .:/app
      - ./logs:/app/logs
    profiles:
      - donotstart

  redis-cli:
    image: redis
    command: redis-cli -h redis-dev
    networks:
      - dev
    environment:
      - TZ=Europe/Moscow
    profiles:
      - donotstart

volumes:
    home_cli_data:

networks:
  dev:
    name: dev
    external: true
